### ISSUE TITLE
Can we have a "OnThreadUpdate" or "OnGithubUpdate" hook?

### ISSUE THREAD

**Issue by SwadicalRag** [willox/hash.js#137]
This is for Facepunch/Github notifications.

I want to be able to programmatically see new posts on facepunch and the thread which the post was submitted to. I had an idea of making a posts versus time graph for the scriptfodder thread to possibly find an algorithm to automatically detect drama (or at least spot it on a graph). it would be hella cool :+1:

We poll facepunch/github at consistent intervals anyway, and I don't see how this will increase the bandwidth usage or CPU usage of hash.

**Comment by meepdarknessmeep** [comment]
:banana:

**Comment by LennyPenny** [comment]
🍆

**Comment by SwadicalRag** [comment]
:baby_bottle: :baby:
```
 /|\
  |
```
:bear:---> 

:o::exclamation: :grey_exclamation: :exclamation:

:baby_bottle: :skull: 

:bear: :-1:
